/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:522876:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:522876:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:782423:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:782423:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:649882:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:649882:

public void imgButton4_click1(GImageButton source, GEvent event) { //_CODE_:imgButton4:562967:
  println("imgButton4 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton4:562967:

public void imgButton5_click1(GImageButton source, GEvent event) { //_CODE_:imgButton5:602840:
  println("imgButton5 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton5:602840:

public void imgButton6_click1(GImageButton source, GEvent event) { //_CODE_:imgButton6:546438:
  println("imgButton6 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton6:546438:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  time = new GLabel(this, 14, 13, 320, 86);
  time.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  time.setText("10:09 AM");
  time.setOpaque(false);
  Calendar = new GLabel(this, 13, 99, 323, 89);
  Calendar.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Calendar.setText("January 1, 2022");
  Calendar.setOpaque(false);
  label1 = new GLabel(this, -8, 1396, 2105, 103);
  label1.setText("        News: ");
  label1.setOpaque(true);
  imgButton1 = new GImageButton(this, 1910, 1290, 60, 60, new String[] { "", "", "" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 1980, 1290, 60, 60, new String[] { "", "", "" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 1840, 1290, 60, 60, new String[] { "", "", "" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  song = new GLabel(this, 1840, 1220, 110, 40);
  song.setText("Song: ");
  song.setOpaque(false);
  label2 = new GLabel(this, 1540, 20, 100, 70);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("My label");
  label2.setOpaque(false);
  label3 = new GLabel(this, 1650, 20, 290, 70);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Cloudy");
  label3.setOpaque(false);
  imgButton4 = new GImageButton(this, 360, 130, 20, 20, new String[] { "", "", "" } );
  imgButton4.addEventHandler(this, "imgButton4_click1");
  imgButton5 = new GImageButton(this, 10, 610, 70, 120, new String[] { "", "", "" } );
  imgButton5.addEventHandler(this, "imgButton5_click1");
  imgButton6 = new GImageButton(this, 1050, 1290, 100, 60, new String[] { "", "", "" } );
  imgButton6.addEventHandler(this, "imgButton6_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel time; 
GLabel Calendar; 
GLabel label1; 
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GLabel song; 
GLabel label2; 
GLabel label3; 
GImageButton imgButton4; 
GImageButton imgButton5; 
GImageButton imgButton6; 
